# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm install -g pnpm
      - name: pnpm install, build, and test
        run: |
          pnpm install
          pnpm build
      # 发布到阿里云
      - name: Deploy to aliyun server
        uses: easingthemes/ssh-deploy@v2.1.5 #可以访问的仓库，实现的上传服务器步骤被封装在此action
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }} #这个是阿里云的私钥
          ARGS: '-avzr --delete'
          SOURCE: 'dist/'
          REMOTE_HOST: '45.76.14.71' #阿里云的 ip
          REMOTE_USER: root #阿里云用户
          TARGET: '/home/static/static/717-ai' #被部署的服务器路径
